version: '3'
services:
  lab:
    image: gomalizingflowjl
    container_name: gomalizingflowjl-lab
    volumes:
      - ./:/work
    working_dir: /work
    ports:
      - "8888:8888"
    command: jupyter lab --notebook-dir /work --ip=0.0.0.0 --allow-root

  lab-gpu:
    image: gomalizingflowjl
    runtime: nvidia
    container_name: gomalizingflowjl-lab-gpu
    volumes:
      - ./:/work
    working_dir: /work
    ports:
      - "8888:8888"
    command: jupyter lab --notebook-dir /work --ip=0.0.0.0 --allow-root

  julia:
    image: gomalizingflowjl
    container_name: gomalizingflowjl-julia
    volumes:
      - ./:/work
    working_dir: /work
    command: julia --project=/work

  julia-gpu:
    image: gomalizingflowjl
    runtime: nvidia
    container_name: gomalizingflowjl-julia-gpu
    volumes:
      - ./:/work
    working_dir: /work
    command: julia --project=/work

  pluto:
    image: gomalizingflowjl
    container_name: gomalizingflowjl-pluto
    volumes:
      - ./:/work
    working_dir: /work
    ports:
      - "9999:9999"
    command: julia -e 'import Pluto; Pluto.run(host="0.0.0.0", port=9999)'
